package survey;
// Generated Feb 23, 2017 6:28:00 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private int userId;
     private String userFname;
     private String userLname;
     private String userEmail;
     private Set<Survey> surveys = new HashSet<Survey>(0);

    public User() {
    }

	
    public User(int userId, String userEmail) {
        this.userId = userId;
        this.userEmail = userEmail;
    }
    public User(int userId, String userFname, String userLname, String userEmail, Set<Survey> surveys) {
       this.userId = userId;
       this.userFname = userFname;
       this.userLname = userLname;
       this.userEmail = userEmail;
       this.surveys = surveys;
    }
   
    public int getUserId() {
        return this.userId;
    }
    
    public void setUserId(int userId) {
        this.userId = userId;
    }
    public String getUserFname() {
        return this.userFname;
    }
    
    public void setUserFname(String userFname) {
        this.userFname = userFname;
    }
    public String getUserLname() {
        return this.userLname;
    }
    
    public void setUserLname(String userLname) {
        this.userLname = userLname;
    }
    public String getUserEmail() {
        return this.userEmail;
    }
    
    public void setUserEmail(String userEmail) {
        this.userEmail = userEmail;
    }
    public Set<Survey> getSurveys() {
        return this.surveys;
    }
    
    public void setSurveys(Set<Survey> surveys) {
        this.surveys = surveys;
    }




}


